
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CORCE = 45;
  public static final int DOSPUNTOS = 27;
  public static final int MULT = 30;
  public static final int RECIVES = 18;
  public static final int CONST = 23;
  public static final int LLAVAP = 46;
  public static final int IDINT = 16;
  public static final int CASE = 15;
  public static final int RESTA = 29;
  public static final int INT = 2;
  public static final int PUNTOCOMA = 25;
  public static final int PARAP = 42;
  public static final int FOR = 10;
  public static final int AND = 39;
  public static final int NOIG = 37;
  public static final int FUN = 6;
  public static final int OR = 40;
  public static final int CALL = 22;
  public static final int DIV = 31;
  public static final int BEGIN = 3;
  public static final int SUMA = 28;
  public static final int IG = 36;
  public static final int IDBOOL = 17;
  public static final int IF = 7;
  public static final int ID = 24;
  public static final int EOF = 0;
  public static final int ASIG = 41;
  public static final int RETURN = 20;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int CORAP = 44;
  public static final int COMA = 26;
  public static final int LLAVCE = 47;
  public static final int DECLARE = 5;
  public static final int SWITCH = 14;
  public static final int NEGAR = 38;
  public static final int PARCE = 43;
  public static final int ELSE = 8;
  public static final int MAYIG = 33;
  public static final int MEN = 34;
  public static final int WHILE = 9;
  public static final int MENORIG = 32;
  public static final int END = 4;
  public static final int NOTHING = 21;
  public static final int RETURNS = 19;
  public static final int FALSE = 13;
  public static final int MAY = 35;
  public static final int DO = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "BEGIN",
  "END",
  "DECLARE",
  "FUN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "DO",
  "TRUE",
  "FALSE",
  "SWITCH",
  "CASE",
  "IDINT",
  "IDBOOL",
  "RECIVES",
  "RETURNS",
  "RETURN",
  "NOTHING",
  "CALL",
  "CONST",
  "ID",
  "PUNTOCOMA",
  "COMA",
  "DOSPUNTOS",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "MENORIG",
  "MAYIG",
  "MEN",
  "MAY",
  "IG",
  "NOIG",
  "NEGAR",
  "AND",
  "OR",
  "ASIG",
  "PARAP",
  "PARCE",
  "CORAP",
  "CORCE",
  "LLAVAP",
  "LLAVCE"
  };
}

